@host = localhost:8000

//register user
POST http://{{host}}/api/user/register
Content-Type: application/application/json

{
    "username": "6jodeci",
    "email": "5jodeci@gmail.com",
    "password": "123465789"
}
###